[[main]]
none = "none"

[[main]]
identifier = "B06tfaZrQp"
name = "2024"
pageRef = "2024"
parent = "CTF"
weight = 9_999

[[main]]
identifier = "BsG3186vWN"
name = "2025"
pageRef = "2025"
parent = "CTF"
weight = 9_999

[[main]]
identifier = "TqaBlQ9nPs"
name = "2026"
pageRef = "2026"
parent = "CTF"
weight = 9_999

[[footer]]
none = "none"
