[[main]]
none = "none"

[[main]]
identifier = "BsG3186vWN"
name = "2025"
pageRef = "2025"
parent = "CTF"
weight = 9_999

[[main]]
identifier = "TqaBlQ9nPs"
name = "2026"
pageRef = "2026"
parent = "CTF"
weight = 9_999

[[main]]
name = "CVE"
pageRef = "CVE"
identifier = "5uEnAM19b2"
weight = 9_999

[[footer]]
none = "none"
