autoSwitchAppearance = true
buymeacoffee = { }
colorScheme = "blowfish"
defaultAppearance = "dark"
defaultBackgroundImage = "lavalamp.svg"
defaultFeaturedImage = "featured.svg"
defaultSocialImage = "/img/blowfish.jpg"
disableImageOptimization = false
disableTextInHeader = false
enableCodeCopy = false
enableSearch = true
fathomAnalytics = { }
firebase = { }
forgejoDefaultServer = "https://v8.next.forgejo.org"
giteaDefaultServer = "https://git.fsfe.org"
highlightCurrentMenuArea = true
replyByEmail = false
rssnext = { }
selineAnalytics = { }
smartTOC = true
smartTOCHideUnfocusedChildren = false
umamiAnalytics = { }
verification = { }

[header]
layout = "fixed-fill-blur"

[footer]
showAppearanceSwitcher = true
showCopyright = true
showMenu = true
showScrollToTop = true
showThemeAttribution = true

[homepage]
cardView = true
cardViewScreenWidth = false
disableHeroImageFilter = false
homepageImage = "featured.svg"
layout = "background"
layoutBackgroundBlur = true
showMoreLink = true
showMoreLinkDest = "/posts/"
showRecent = true
showRecentItems = 12

[article]
editAppendPath = true
heroStyle = "background"
invertPagination = false
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
relatedContentLimit = 6
seriesOpened = false
sharingLinks = [
  "linkedin",
  "twitter",
  "bluesky",
  "reddit",
  "whatsapp",
  "telegram",
  "pinterest",
  "facebook",
  "email"
]
showAuthor = true
showAuthorsBadges = true
showBreadcrumbs = true
showCategoryOnly = true
showDate = true
showDateOnlyInArticle = false
showDateUpdated = false
showDraftLabel = true
showEdit = false
showHeadingAnchors = true
showHero = true
showLikes = true
showPagination = true
showReadingTime = true
showRelatedContent = true
showTableOfContents = true
showTaxonomies = true
showViews = true
showWordCount = false
showZenMode = true

[list]
cardView = true
cardViewScreenWidth = false
constrainItemsWidth = false
groupByYear = false
heroStyle = "background"
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = false
orderByWeight = true
showBreadcrumbs = false
showCards = true
showHero = true
showLikes = false
showSummary = false
showTableOfContents = true
showViews = false

[sitemap]
excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
cardView = false
heroStyle = "background"
showBreadcrumbs = false
showHero = true
showLikes = false
showTableOfContents = true
showTermCount = true
showViews = false

[term]
cardView = true
cardViewScreenWidth = false
groupByYear = false
heroStyle = "background"
showBreadcrumbs = false
showHero = true
showLikes = false
showTableOfContents = true
showViews = false
